### ISSUE TITLE
Cookie Jar

### ISSUE THREAD

**Issue by jamesarosen** [halorgium/rack-client#1]
I'm not sure whether Rack itself already contains a cookie jar (but it would be odd if it did), but Rack-Client seems like the perfect way to answer [this question on StackOverflow](http://stackoverflow.com/questions/2615815/how-to-store-cookies-in-ruby). We should (a) make a cookie jar if no such thing exists in Rack-Client and (b) compose a good answer to the question.

**Comment by halorgium** [comment]
Turns out `CookieJar` was added just before this was filed. 
It doesn't have the same features as `Mechanize` with serialization and storage.
