### ISSUE TITLE
Ruby 1.9.2 warning

### ISSUE THREAD

**Issue by fbjork** [halorgium/rack-client#2]
Getting this warning when I updated to Ruby 1.9.2:

/Users/fredrik/.rvm/gems/ruby-1.9.2-p0/gems/rack-client-0.3.0/lib/rack/client/parser/body_collection.rb:4: warning: undefining `object_id' may cause serious problems

**Comment by mattetti** [comment]
fixed in my repo: http://github.com/mattetti/rack-client/commit/4cb8e1a9edacc4d692f44706316ffc8b95df38a1

**Comment by benburkert** [comment]
appears to be fixed in HEAD, thanks!
